services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
      - ./frontend/node_modules:/app/node_modules
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    ports:
      - 5000:5000
    volumes:
      - ./backend:/app
  # firebase:
  #   build:
  #     context: ./firebase
  #     dockerfile: Dockerfile
  #   ports:
  #     - 4000:4000
  #     - 9099:9099
  #     - 9000:9000
  #   volumes:
  #     - ./firebase:/firebase